export default {
  login: "andrew",
  id: 1060,
  node_id: "MDQ6VXNlcjEwNjA=",
  avatar_url: "https://avatars2.githubusercontent.com/u/1060?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/andrew",
  html_url: "https://github.com/andrew",
  followers_url: "https://api.github.com/users/andrew/followers",
  following_url: "https://api.github.com/users/andrew/following{/other_user}",
  gists_url: "https://api.github.com/users/andrew/gists{/gist_id}",
  starred_url: "https://api.github.com/users/andrew/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/andrew/subscriptions",
  organizations_url: "https://api.github.com/users/andrew/orgs",
  repos_url: "https://api.github.com/users/andrew/repos",
  events_url: "https://api.github.com/users/andrew/events{/privacy}",
  received_events_url: "https://api.github.com/users/andrew/received_events",
  type: "User",
  site_admin: false,
  name: "Andrew Nesbitt",
  company: null,
  blog: "https://nesbitt.io",
  location: "UK",
  email: null,
  hireable: null,
  bio: "Software engineer and researcher",
  twitter_username: "teabass",
  public_repos: 293,
  public_gists: 192,
  followers: 2508,
  following: 3149,
  created_at: "2008-02-27T11:39:22Z",
  updated_at: "2020-12-08T20:13:52Z",
};
